---
title: "Trash fish deterioration analysis"
format: html
---

#Preperation 
##Load packages
```{r}
library(tidyverse)
library(ggplot2)
library(car)
library(glmmTMB)
library(mgcv)
library(mgcViz)
library(multcomp)
library(emmeans)
library(DHARMa)
library(powerjoin)
library(paletteer)
library(fishualize)
library(vegan)
library(ggsignif)
library(ggpubr)
library(reshape2)
library("Hmisc")
library(corrplot)

set.seed(42)
```

##Load data
```{r}
deterior_sense <- read_csv('../data/1.3-2024-1-1_Deterioration_sensory_scores.csv', trim_ws = TRUE, na = c("", "NA","na"))
deterior_chem <- read_csv('../data/1.3-2024-1-1_Deterioration_chem.csv', trim_ws = TRUE, na = c("", "na", "NA"))
deterior_sp <- read_csv('../data/1.3-2024-1-1_Deterioration_fishsp.csv', trim_ws = TRUE, na = c("", "na", "NA"))

deterior_sense <- deterior_sense |>  
  dplyr::mutate(treatment = as.factor(treatment), 
                replicate = as.factor(replicate),
                sample = as.factor(paste(treatment, day, sep = "_")))

deterior_chem <- deterior_chem |>  
  dplyr::mutate(treatment = as.factor(treatment), 
                replicate = as.factor(replicate), 
                sample = paste(treatment, day, subsample, sep = "_"),
                ss_sample = as.factor(paste(treatment, day, subsample, sep = "_")))

deterior_sp <- deterior_sp |>  
  dplyr::mutate(treatment = as.factor(treatment)) |> 
  dplyr::group_by(treatment, day) |> 
  dplyr::mutate(total_count = sum(Count), 
                proportion = Count/total_count, 
                sample = as.factor(paste(treatment, day, sep = "_")))
``` 

##Species composition
```{r}
deterior_sp |> 
  dplyr::group_by(Genus, Species) |> 
  dplyr::summarise(mean(proportion), 
                   sd(proportion)) |> 
  as.data.frame()
  
deterior_sp |> 
  dplyr::group_by(treatment, day) |> 
  dplyr::summarise(count = min(total_count)) |> 
  dplyr::ungroup() |> 
  dplyr::summarise(mean(count), 
                   sd(count))

deterior_sp |> 
  filter(Count>1) |> 
  dplyr::group_by(Genus, Species) |> 
  dplyr::summarise(mean(proportion), 
                   sd(proportion))
```

#Sensory Assessment
##Mucous
```{r}
deterior_mucous_glm <- glmmTMB(Mucous ~ treatment*poly(day,2) + (1|sample),
                               data = deterior_sense, 
                               family = gaussian)


#checking fit
simulateResiduals(deterior_mucous_glm, plot = TRUE)     #good
hist(simulateResiduals(deterior_mucous_glm))            #good

#summary
summary(deterior_mucous_glm) 
#changes by day, not treatment 

#compare at the days
deterior_mucous_glm |> 
  emmeans(~treatment*day, at = list(day = c(unique(deterior_sense$day))), type = "response") |> 
  pairs() |> 
  summary(infer = TRUE)

#plot
mucous_deterior <- deterior_sense |>  
  ggplot(aes(x = day, y = Mucous)) + 
  geom_jitter(size = 2, 
             aes(shape = treatment, colour = treatment), 
             width = 0.05, height = 0.05) + 
  geom_smooth(method = "lm", 
              formula = y ~ poly(x, 2), 
              alpha = 0.3, 
              aes(fill = treatment, colour = treatment)) + 
  scale_colour_paletteer_d("ggthemes::Color_Blind", 
                           labels = c("1:1", "2:1"), name = "Ice:Fish ratio") + 
  scale_shape_discrete(labels = c("1:1", "2:1"), name = "Ice:Fish ratio")+
  scale_fill_paletteer_d("ggthemes::Color_Blind", guide = "none") +
  theme_minimal() +
  scale_x_continuous(name = "", 
                     breaks = seq(0, 5, 1)) + 
  scale_y_continuous(limits = c(1, 10.5), 
                     breaks = seq(1, 10, 1), 
                     name = "Mucous score") + 
  theme(axis.line = element_line(colour = "black"), 
        legend.text = element_text(colour = "black"), 
        axis.text = element_text(colour = "black"), 
        panel.grid.minor = element_blank(), 
        axis.ticks = element_line(colour = "black"), 
        legend.position = "none")
```

##Eye_Clarity
```{r}
deterior_eyeclarity_glm <- glmmTMB(Eye_Clarity ~ treatment*poly(day,3) + (1|sample),
                               data = deterior_sense, 
                               family = gaussian)

#checking fit
simulateResiduals(deterior_eyeclarity_glm, plot = TRUE)     #good
hist(simulateResiduals(deterior_eyeclarity_glm))            #one outliers

#summary
summary(deterior_eyeclarity_glm) 

deterior_eyeclarity_glm |> 
  emmeans(~treatment, type = "response") |> 
  pairs()
#Minor effect treatment?

#compare at the days
deterior_eyeclarity_glm |> 
  emmeans(~treatment*day, at = list(day = c(unique(deterior_sense$day))), type = "response") |> 
  pairs() |> 
  summary(infer = TRUE)

#plot
eye_deterior <- deterior_sense |>  
  ggplot(aes(x = day, y = Eye_Clarity)) + 
  geom_jitter(size = 2, 
             aes(shape = treatment, colour = treatment), 
             width = 0.05, height = 0.05) + 
  geom_smooth(method = "lm", 
              formula = y ~ poly(x, 3),
              alpha = 0.3, 
              aes(fill = treatment, colour = treatment)) + 
  scale_colour_paletteer_d("ggthemes::Color_Blind", 
                           labels = c("1:1", "2:1"), name = "Ice:Fish ratio", guide = "none") + 
  scale_shape_discrete(labels = c("1:1", "2:1"), name = "Ice:Fish ratio", guide = "none")+
  scale_fill_paletteer_d("ggthemes::Color_Blind", guide = "none") +
  theme_minimal() +
  scale_x_continuous(name = "", 
                     breaks = seq(0, 5, 1)) + 
  scale_y_continuous(limits = c(1, 10.5), 
                     breaks = seq(1, 10, 1), 
                     name = "Eye Clarity score") + 
  theme(axis.line = element_line(colour = "black"), 
        legend.text = element_text(colour = "black"), 
        axis.text = element_text(colour = "black"), 
        panel.grid.minor = element_blank(), 
        axis.ticks = element_line(colour = "black"))
```

##Odor
```{r}
deterior_odor_glm <- glmmTMB(Odor ~ treatment*poly(day,4) + (1|sample),
                             data = deterior_sense, 
                             dispformula = ~day,
                             family = gaussian)
#checking fit
simulateResiduals(deterior_odor_glm, plot = TRUE)     #good
hist(simulateResiduals(deterior_odor_glm))            #one outlier

#summary
summary(deterior_odor_glm) 
#day effects and treatment effects

deterior_sense |> 
  group_by(treatment, day) |> 
  summarise(mean(Odor))

#compare at the days
deterior_odor_glm |> 
  emmeans(~treatment*day, at = list(day = c(unique(deterior_sense$day))), type = "response") |> 
  pairs() |> 
  summary(infer = TRUE)

#plot
odor_deterior <- 
  deterior_sense |>  
  ggplot(aes(x = day, y = Odor)) + 
  geom_jitter(size = 2, 
             aes(shape = treatment, colour = treatment), 
             width = 0.05, height = 0.05) + 
  geom_smooth(method = "lm", 
              formula = y ~ poly(x, 4),
              alpha = 0.3, 
              aes(fill = treatment, colour = treatment)) + 
  scale_colour_paletteer_d("ggthemes::Color_Blind", 
                           labels = c("1:1", "2:1"), name = "Ice:Fish ratio", guide = "none") + 
  scale_shape_discrete(labels = c("1:1", "2:1"), name = "Ice:Fish ratio", guide = "none")+
  scale_fill_paletteer_d("ggthemes::Color_Blind", guide = "none", position = "bottom") +
  theme_minimal() +
  scale_x_continuous(name = "Day", 
                     breaks = seq(0, 5, 1)) + 
  scale_y_continuous(limits = c(1, 10.5), 
                     breaks = seq(1, 10, 1), 
                     name = "Odor score") + 
  theme(axis.line = element_line(colour = "black"), 
        legend.text = element_text(colour = "black"), 
        axis.text = element_text(colour = "black"), 
        panel.grid.minor = element_blank(), 
        axis.ticks = element_line(colour = "black"), 
        legend.position = "bottom")
```

#Chemical and biological indicators
##pH
```{r}
deterior_pH_glm_poly5_1 <- glmmTMB(pH ~ treatment*poly(day, 5) + (1|ss_sample), 
        data = deterior_chem, 
        family = gaussian)

#checking fit
simulateResiduals(deterior_pH_glm_poly5_1, plot = TRUE)     #good
hist(simulateResiduals(deterior_pH_glm_poly5_1))            #good
summary(deterior_pH_glm_poly5_1)  

#compare at the days
deterior_pH_glm_poly5_1 |> 
  emmeans(~treatment*day, at = list(day = c(unique(deterior_chem$day))), type = "response") |> 
  pairs() |> 
  summary(infer = TRUE)

deterior_chem |>  
  group_by(treatment, day) |> 
  dplyr::summarise(mean(pH), 
                   sd(pH))

#plot
ph_deterior <- 
  deterior_chem |>  
  ggplot(aes(x = day, y = pH)) + 
  geom_jitter(size = 2, 
             aes(shape = treatment, colour = treatment), 
              width = 0.05, height = 0.05) + 
  geom_smooth(method = lm, 
              formula = y ~ poly(x, 5), 
              alpha = 0.3, 
              aes(fill = treatment, colour = treatment)) + 
  scale_colour_paletteer_d("ggthemes::Color_Blind", 
                           labels = c("1:1", "2:1"), name = "Ice:Fish ratio") + 
  scale_shape_discrete(labels = c("1:1", "2:1"), name = "Ice:Fish ratio")+
  scale_fill_paletteer_d("ggthemes::Color_Blind", guide = "none") +
  theme_minimal() +
  scale_x_continuous(name = "", 
                     breaks = seq(0, 5, 1)) + 
  scale_y_continuous(limits = c(6.6, 7.1), 
                     breaks = seq(6.6, 7.1, 0.1), 
                     name = "pH") + 
  theme(axis.line = element_line(colour = "black"), 
        legend.text = element_text(colour = "black"), 
        axis.text = element_text(colour = "black"), 
        panel.grid.minor = element_blank(), 
        axis.ticks = element_line(colour = "black"), 
        legend.position = "none")
```

##TVB-N
```{r}
glm_deter_TBVN <- glmmTMB(`TVB-N` ~ poly(day,2)*treatment + (1|ss_sample), 
                              data = deterior_chem,
                              family = gaussian())
#checking fit
simulateResiduals(glm_deter_TBVN, plot = TRUE)     #good
hist(simulateResiduals(glm_deter_TBVN))            #one outlier
testZeroInflation(glm_deter_TBVN)                  #good

summary(glm_deter_TBVN) 
#everything influences

#compare at the days
glm_deter_TBVN |> 
  emmeans(~treatment*day, at = list(day = c(unique(deterior_chem$day))), type = "response") |> 
  pairs() |> 
  summary(infer = TRUE)

deterior_chem |> 
  group_by(treatment, day) |> 
  summarise(mean(`TVB-N`), 
            sd(`TVB-N`), 
            mean(TVC, na.rm = TRUE), 
            sd(TVC,na.rm = TRUE))

#plot
TVBN_deterior <- 
  deterior_chem |>  
  ggplot(aes(x = day, y = `TVB-N`)) + 
  geom_jitter(size = 2, 
             aes(shape = treatment, colour = treatment), 
              width = 0.05, height = 0.05) + 
  geom_smooth(method = "lm", 
              formula = y~poly(x, 2), 
              alpha = 0.3, 
              aes(fill = treatment, colour = treatment)) +
  geom_hline(yintercept = 35, 
             colour = "black", 
             linetype = "dashed", 
             size = 1) +
  scale_colour_paletteer_d("ggthemes::Color_Blind", 
                           labels = c("1:1", "2:1"), name = "Ice:Fish ratio") + 
  scale_shape_discrete(labels = c("1:1", "2:1"), name = "Ice:Fish ratio")+
  scale_fill_paletteer_d("ggthemes::Color_Blind", guide = "none") +
  theme_minimal() +
  scale_x_continuous(name = "", 
                     breaks = seq(0, 5, 1)) + 
  scale_y_continuous(limits = c(20, 45), 
                     breaks = seq(20, 45, 5), 
                     name = "TVB-N (mg/100g)") + 
  theme(axis.line = element_line(colour = "black"), 
        legend.text = element_text(colour = "black"), 
        axis.text = element_text(colour = "black"), 
        panel.grid.minor = element_blank(), 
        axis.ticks = element_line(colour = "black"), 
        legend.position = "none")
```

##TVC
```{r}
deterior_chem_TVC <- deterior_chem |>  
  dplyr::filter(replicate %in% c("1", "2", "3")) |> 
  dplyr::mutate(TVC = as.numeric(TVC, na.rm = TRUE)) |>  
  dplyr::filter(!is.na(TVC))

glm_deter_TVC <- glmmTMB(TVC ~ poly(day, 4)*treatment + (1|ss_sample), 
                              data = deterior_chem_TVC,
                              family = gaussian())
#checking fit
simulateResiduals(glm_deter_TVC, plot = TRUE)     #good
hist(simulateResiduals(glm_deter_TVC))            #one outlier

summary(glm_deter_TVC) 
#everything influences

#compare at the days
glm_deter_TVC |> 
  emmeans(~treatment*day, at = list(day = c(unique(deterior_chem$day))), type = "response") |> 
  pairs() |> 
  summary(infer = TRUE)

#plot
TVC_deterior <- 
  deterior_chem_TVC |>  
  ggplot(aes(x = day, y = TVC)) + 
  geom_jitter(size = 2, 
             aes(shape = treatment, colour = treatment), 
              width = 0.05, height = 0.05) + 
  geom_smooth(method = "lm", 
              formula = y~poly(x, 4), 
              alpha = 0.3, 
              aes(fill = treatment, colour = treatment)) + 
  geom_hline(yintercept = 7, 
             colour = "black", 
             linetype = "dashed", 
             size = 1) +
  scale_colour_paletteer_d("ggthemes::Color_Blind", 
                           labels = c("1:1", "2:1"), name = "Ice:Fish ratio", guide = "none") + 
  scale_shape_discrete(labels = c("1:1", "2:1"), name = "Ice:Fish ratio", guide = "none")+
  scale_fill_paletteer_d("ggthemes::Color_Blind", guide = "none") +
  theme_minimal() +
  scale_x_continuous(name = "Day", 
                     breaks = seq(0, 5, 1)) + 
  scale_y_continuous(limits = c(5, 8), 
                     breaks = seq(5, 8, 1), 
                     name = "TVC (log10 CFU/g)") + 
  theme(axis.line = element_line(colour = "black"), 
        legend.text = element_text(colour = "black"), 
        axis.text = element_text(colour = "black"), 
        panel.grid.minor = element_blank(), 
        axis.ticks = element_line(colour = "black"), 
        legend.position = "bottom")
```

#Combine plots
```{r}
ggarrange(mucous_deterior, eye_deterior, odor_deterior, nrow = 3, ncol = 1, labels = c("a", "b", "c"))

ggarrange(ph_deterior, TVBN_deterior, TVC_deterior, nrow = 3, ncol = 1, labels = c("a", "b", "c"))
```

